# Created using wingetcreate 0.3.0.3
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: KristenMcWilliam.Nyrna
PackageVersion: 2.1.0
Installers:
- Architecture: x64
  InstallerType: inno
  InstallerUrl: https://github.com/Merrit/nyrna/releases/download/v2.1.0/nyrna-windows-installer.exe
  InstallerSha256: 5F11F3B979E346CE57D27B06AEE3D1BD435D6EE6C72ADB754DE562AEA1B240C4
ManifestType: installer
ManifestVersion: 1.0.0

